#!/bin/bash

#echo Testing, wheter Java binary is of correct version...
if ! java -version 2>&1 | head -n1 | grep version\ \"11 > /dev/null; then
	echo "Java 11 is required!"
	exit 1
fi


java -server -XX:+UnlockExperimentalVMOptions -XX:+EnableJVMCI\
	--module-path=graal/sdk/mxbuild/dists/jdk11/graal-sdk.jar:graal/truffle/mxbuild/dists/jdk11/truffle-api.jar\
	--upgrade-module-path=graal.instrumented.jar:graal/compiler/mxbuild/dists/jdk11/graal-management.jar\
	-XX:+UseJVMCICompiler\
	--add-opens java.base/java.lang.reflect=jdk.internal.vm.compiler\
	"$@"
