#!/bin/bash

if ! java -version 2>&1 | head -n1 | grep 'version "11' > /dev/null; then
	echo "Java 11 is required!"
	exit 1
fi

gcopdd="`dirname "$0"`"
graal="$gcopdd/graal"

java -server -XX:+UnlockExperimentalVMOptions -XX:+EnableJVMCI\
	--module-path="$graal/sdk/mxbuild/dists/jdk11/graal-sdk.jar":"$graal/truffle/mxbuild/dists/jdk11/truffle-api.jar" \
	--upgrade-module-path="$gcopdd/graal.instrumented.jar":"$graal/compiler/mxbuild/dists/jdk11/graal-management.jar" \
	-XX:+UseJVMCICompiler \
	-Dblood.dumpsdir="$gcopdd/dumps" \
	"$@"
