#!/bin/bash -e

cd "$(git rev-parse --show-toplevel)/dumps"

dump_browser_py='python3 ../tools/dump_browser.py'

cmd_0() {
	$dump_browser_py
}

cmd_1start() {
	nohup $dump_browser_py > /dev/null 2> /dev/null &
}

cmd_1stop() {
	wget -o /dev/null -O /dev/null 'http://localhost:8000/STOP'
}

cmd_1save() {
	cmd_1start
	[ -e html ] && rm -rf html
	mkdir html
	# wait until server starts
	while ! wget -o /dev/null -O /dev/null 'http://localhost:8000/'; do :; done
	# recursive download to dumps/html/
	wget -o /dev/null -r --convert-links -P html -E -nH 'http://localhost:8000/'
	cmd_1stop
}

"cmd_$#$1"
